In [2]:
import pandas as pd

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [3]:
data = pd.read_html('https://fbref.com/en/comps/Big5/Big-5-European-Leagues-Stats', attrs={"id":"big5_table"})[0]

In [4]:
data.head()

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,...,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper
0,1,Inter,it ITA,1,34,28,5,1,81,18,...,89,2.62,72.7,27.5,45.2,1.29,W D W W L,68838,Lautaro Martínez - 23,Yann Sommer
1,2,Leverkusen,de GER,1,31,25,6,0,77,22,...,81,2.61,66.9,28.4,38.5,1.20,W W D D W,29980,Victor Boniface - 12,Lukáš Hrádecký
2,3,Real Madrid,es ESP,1,33,26,6,1,71,22,...,84,2.55,62.8,30.7,32.1,0.94,W W W W W,72153,Jude Bellingham - 18,Andriy Lunin
3,4,Manchester City,eng ENG,2,35,25,7,3,87,33,...,82,2.34,73.0,33.5,39.6,1.13,W W W W W,52896,Erling Haaland - 25,Ederson
4,5,Arsenal,eng ENG,1,36,26,5,5,88,28,...,83,2.31,71.7,26.8,44.9,1.25,L W W W W,60232,Bukayo Saka - 16,David Raya

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Rk               96 non-null     int64
 1   Squad            96 non-null     object
 2   Country          96 non-null     object
 3   LgRk             96 non-null     int64
 4   MP               96 non-null     int64
 5   W                96 non-null     int64
 6   D                96 non-null     int64
 7   L                96 non-null     int64
 8   GF               96 non-null     int64
 9   GA               96 non-null     int64
 10  GD               96 non-null     int64
 11  Pts              96 non-null     int64
 12  Pts/MP           96 non-null     float64
 13  xG               96 non-null     float64
 14  xGA              96 non-null     float64
 15  xGD              96 non-null     float64
 16  xGD/90           96 non-null     float64
 17  Last 5           96 non-null     object
 18  Attendance       96 non-null     int64
 19  Top Team Scorer  96 non-null     object
 20  Goalkeeper       96 non-null     object
dtypes: float64(5), int64(11), object(5)
memory usage: 15.9+ KB

In [6]:
data.isnull().sum()

Rk                 0
Squad              0
Country            0
LgRk               0
MP                 0
W                  0
D                  0
L                  0
GF                 0
GA                 0
GD                 0
Pts                0
Pts/MP             0
xG                 0
xGA                0
xGD                0
xGD/90             0
Last 5             0
Attendance         0
Top Team Scorer    0
Goalkeeper         0
dtype: int64

In [7]:
data['Country'].unique()

array(['it ITA', 'de GER', 'es ESP', 'eng ENG', 'fr FRA'], dtype=object)

In [8]:
data['Country'] = data['Country'].replace({
    'it ITA': 'Italy', 
    'de GER': 'Germany', 
    'es ESP': 'Spain', 
    'eng ENG': 'England', 
    'fr FRA': 'France'
})

data.head()

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,...,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper
0,1,Inter,Italy,1,34,28,5,1,81,18,...,89,2.62,72.7,27.5,45.2,1.29,W D W W L,68838,Lautaro Martínez - 23,Yann Sommer
1,2,Leverkusen,Germany,1,31,25,6,0,77,22,...,81,2.61,66.9,28.4,38.5,1.20,W W D D W,29980,Victor Boniface - 12,Lukáš Hrádecký
2,3,Real Madrid,Spain,1,33,26,6,1,71,22,...,84,2.55,62.8,30.7,32.1,0.94,W W W W W,72153,Jude Bellingham - 18,Andriy Lunin
3,4,Manchester City,England,2,35,25,7,3,87,33,...,82,2.34,73.0,33.5,39.6,1.13,W W W W W,52896,Erling Haaland - 25,Ederson
4,5,Arsenal,England,1,36,26,5,5,88,28,...,83,2.31,71.7,26.8,44.9,1.25,L W W W W,60232,Bukayo Saka - 16,David Raya

In [9]:
data['last_5_list'] = data['Last 5'].str.split()

data['last_5_wins'] = data['last_5_list'].apply(lambda x: x.count('W'))
data['last_5_loss'] = data['last_5_list'].apply(lambda x: x.count('L'))

data.head()

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,...,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,last_5_list,last_5_wins,last_5_loss
0,1,Inter,Italy,1,34,28,5,1,81,18,...,27.5,45.2,1.29,W D W W L,68838,Lautaro Martínez - 23,Yann Sommer,"[W, D, W, W, L]",3,1
1,2,Leverkusen,Germany,1,31,25,6,0,77,22,...,28.4,38.5,1.20,W W D D W,29980,Victor Boniface - 12,Lukáš Hrádecký,"[W, W, D, D, W]",3,0
2,3,Real Madrid,Spain,1,33,26,6,1,71,22,...,30.7,32.1,0.94,W W W W W,72153,Jude Bellingham - 18,Andriy Lunin,"[W, W, W, W, W]",5,0
3,4,Manchester City,England,2,35,25,7,3,87,33,...,33.5,39.6,1.13,W W W W W,52896,Erling Haaland - 25,Ederson,"[W, W, W, W, W]",5,0
4,5,Arsenal,England,1,36,26,5,5,88,28,...,26.8,44.9,1.25,L W W W W,60232,Bukayo Saka - 16,David Raya,"[L, W, W, W, W]",4,1

In [10]:
data = data.drop('last_5_list', axis=1)
data.head()

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,...,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper,last_5_wins,last_5_loss
0,1,Inter,Italy,1,34,28,5,1,81,18,...,72.7,27.5,45.2,1.29,W D W W L,68838,Lautaro Martínez - 23,Yann Sommer,3,1
1,2,Leverkusen,Germany,1,31,25,6,0,77,22,...,66.9,28.4,38.5,1.20,W W D D W,29980,Victor Boniface - 12,Lukáš Hrádecký,3,0
2,3,Real Madrid,Spain,1,33,26,6,1,71,22,...,62.8,30.7,32.1,0.94,W W W W W,72153,Jude Bellingham - 18,Andriy Lunin,5,0
3,4,Manchester City,England,2,35,25,7,3,87,33,...,73.0,33.5,39.6,1.13,W W W W W,52896,Erling Haaland - 25,Ederson,5,0
4,5,Arsenal,England,1,36,26,5,5,88,28,...,71.7,26.8,44.9,1.25,L W W W W,60232,Bukayo Saka - 16,David Raya,4,1